### ISSUE TITLE
impl Clone for Dir

### ISSUE THREAD

**Issue by Ekleog** [tailhook/openat#32]
Hello,

I've been trying out this crate recently, and it looks pretty neat :) However, I've just hit a small issue: it looks like there's no way to `Clone` a `Dir` for now.

I totally can work around that, be it by using `Arc<Dir>` or `from_raw_fd(dup(as_raw_fd(d)))`, but I just wanted to let you know that it's part of the API that could deserve improvement, probably by just doing the raw_fd dance in the `Clone` impl :)

What do you think about this?

**Comment by tailhook** [comment]
Hi!

We can't do `dup` in clone, because `dup` is a fallible operation. And also it's quite expensive in the cases where `Arc<Dir>` is sufficient.

I think wrapping into an `Arc` is a recommended way. I think the reason than there is no inner `Arc` is to lower overhead and to build abstractions on top easier (e.g. `struct MyDir(Path, Dir); Arc<MyDir>` doesn't have double wrapping into an `Arc`).

**Comment by Ekleog** [comment]
Oh, that's totally true :) but then maybe a `try_clone`, like `File` has? (not having an inner `Arc` totally makes sense to me too)

**Comment by tailhook** [comment]
Yes `try_clone` makes sense for me. Do you want to make a PR?

**Comment by Ekleog** [comment]
It's taken me a bit of time, but here it comes :) https://github.com/tailhook/openat/pull/33

**Comment by tailhook** [comment]
Released as v0.1.19
